* Add patch from Adrien Bustany:
Don't hardcode qmake path

The qmake utility is called qmake-qt4 on some distributions, as Fedora.
This commit adds a simple detection mechanism to check for qmake or
qmake-qt4 presence.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -72,6 +72,19 @@ OPT_SHADOW=maybe
 
 PERL=`$WHICH perl 2>/dev/null`
 
+QMAKE=`$WHICH qmake 2>/dev/null`
+
+if [ -z "$QMAKE" ] ; then
+	QMAKE=`$WHICH qmake-qt4 2>/dev/null`
+fi
+
+if [ -z "$QMAKE" ] ; then
+	echo
+	echo "You need qmake in your PATH to build QSparql."
+	echo "Cannot proceed."
+	exit 1
+fi
+
 # is this a shadow build?
 if [ "$OPT_SHADOW" = "maybe" ]; then
     OPT_SHADOW=no
